spring:
  zipkin:
    base-url: http://localhost:9411/

app:
  rabbitmq:
    notify-pizzas-added-routingkey: q.notify-pizzas-added-to-restaurant
    
server:
  port: 0 #9092
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka