spring:
  zipkin:
    base-url: http://localhost:9411/
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/RestaurantServiceDB;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 0 #9091
  servlet:
    context-path: /api 

app:
  pizza-service-url: http://localhost:9090/api/pizzas/restaurant
  rabbitmq:
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    notify-pizzas-added-routingkey: q.notify-pizzas-added-to-restaurant
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      addPizzasToRestaurantCircuitBreaker:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
  retry:
    retry-aspect-order: 2
    instances:
      retryAddPizzasToRestaurant:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
